#include <stdio.h>
#include <cs50.h>
#include <ctype.h>
#include <string.h>
//put a line that corrlates the point system of scrabble to the lines entered
int Points[] = {1, 3, 3, 2, 1, 4, 2, 4, 1, 8, 5, 1, 3, 1, 1, 3, 10, 1, 1, 1, 1, 4, 4, 8, 4, 10};

int compute_score(string word);

int main(void){
    //asks for user input for the words they wish to type
    string word1 = get_string("Player 1: ");
    string word2 = get_string("Player 2: ");

    //the code to calculate the words entered
    int score1 = compute_score(word1);
    int score2 = compute_score(word2);

    //three way fork to determine the results
    if(score1 > score2){
        printf("Player 1 wins\n");
    }

    else if(score2 > score1){
        printf("Player 2 wins\n");
    }

    else{
        printf("Tie!\n");
    }
}

int compute_score(string word){

    //starting value
    int score = 0;

    //program to calculate the words entered
    for(int i = 0, len = strlen(word); i < len; i++)
    if(isupper(word[i])){
        score += Points[word[i] - 'A'];
    }

    else if(islower(word[i])){
        score += Points[word[i] - 'a'];
    }
    return score;
}

/*
cs50/problems/2025/x/scrabble

:) scrabble.c exists
Log
checking that scrabble.c exists...

:) scrabble.c compiles
Log
running clang scrabble.c -o scrabble -std=c11 -ggdb -lm -lcs50...

:) handles letter cases correctly
Log
running ./scrabble...
sending input LETTERCASE...
sending input lettercase...
checking for output "Tie!"...
checking that program exited with status 0...

:) handles punctuation correctly
Log
running ./scrabble...
sending input Punctuation!?!?...
sending input punctuation...
checking for output "Tie!"...
checking that program exited with status 0...

:) correctly identifies 'Question?' and 'Question!' as a tie
Log
running ./scrabble...
sending input Question?...
sending input Question!...
checking for output "Tie!"...
checking that program exited with status 0...

:) correctly identifies 'drawing' and 'illustration' as a tie
Log
running ./scrabble...
sending input drawing...
sending input illustration...
checking for output "Tie!"...
checking that program exited with status 0...

:) correctly identifies 'hai!' as winner over 'Oh,'
Log
running ./scrabble...
sending input Oh,...
sending input hai!...
checking for output "Player 2 wins!"...
checking that program exited with status 0...

:) correctly identifies 'COMPUTER' as winner over 'science'
Log
running ./scrabble...
sending input COMPUTER...
sending input science...
checking for output "Player 1 wins!"...
checking that program exited with status 0...

:) correctly identifies 'Scrabble' as winner over 'wiNNeR'
Log
running ./scrabble...
sending input Scrabble...
sending input wiNNeR...
checking for output "Player 1 wins!"...
checking that program exited with status 0...

:) correctly identifies 'pig' as winner over 'dog'
Log
running ./scrabble...
sending input pig...
sending input dog...
checking for output "Player 1 wins!"...
checking that program exited with status 0...

:) correctly identifies 'Skating!' as winner over 'figure?'
Log
running ./scrabble...
sending input figure?...
sending input Skating!...
checking for output "Player 2 wins!"...
checking that program exited with status 0...

:) correctly identifies winner between random words
Log
running ./scrabble...
sending input j...
sending input k...
checking for output "Player 1 wins!"...
checking that program exited with status 0...
running ./scrabble...
sending input d...
sending input e...
checking for output "Player 1 wins!"...
checking that program exited with status 0...
running ./scrabble...
sending input c...
sending input d...
checking for output "Player 1 wins!"...
checking that program exited with status 0...
running ./scrabble...
sending input x...
sending input y...
checking for output "Player 1 wins!"...
checking that program exited with status 0...
running ./scrabble...
sending input e...
sending input f...
checking for output "Player 2 wins!"...
checking that program exited with status 0...

:) implementation correctly calculates scores using the Scrabble points table
Log
running ./scrabble...
sending input x...
sending input rrrrrrrr...
checking for output "Tie!"...
checking that program exited with status 0...
running ./scrabble...
sending input k...
sending input lllll...
checking for output "Tie!"...
checking that program exited with status 0...
running ./scrabble...
sending input t...
sending input n...
checking for output "Tie!"...
*/
