#include <ctype.h>
#include <cs50.h>
#include <math.h>
#include <stdio.h>
#include <string.h>
    //index = 0.0588 * L - 0.296 * S - 15.8;
int count_letters(string text);
int count_words(string text);
int count_sentences(string text);

int main(void){
    //get user input for text
    string text = get_string("Text: ");

    int letters = count_letters(text);
    int words = count_words(text);
    int sentences = count_sentences(text);

    float L = ((float) letters / words) * 100;
    float S = ((float) sentences / words) * 100;

    float index = 0.0588 * L - 0.296 * S - 15.8;

    int grade = (int) round(index);
    if (grade < 1)
    {
        printf("Before Grade 1\n");
    }
    // Case 2: Grade 16+
    else if (grade >= 16)
    {
        printf("Grade 16+\n");
    }
    // Case 3: All other grades (Grade 1 through 15)
    else
    {
        printf("Grade %i\n", grade);
    }
}
    // count the number of letters, words, and sentences the user inputs
    // compute using the index

    // print the grade level using a system that matches the index to a specific grade level
int count_letters(string text){
    //returns the number of letters within the string
    int letter_count = 0;
    for(int i = 0; i < strlen(text); i++){
        isalpha(text[i]);
        if(isalpha(text[i])){
            letter_count++;
        }
    }
    return letter_count;
}

int count_words(string text){
    //returns the number of words within the string
    int word_count = 1;
     for(int i = 0; i < strlen(text); i++){
        if(isspace(text[i])){
            // If it is a space, it marks the beginning of the next word.
            word_count++;
        }

    }
    return word_count;
}

int count_sentences(string text){
    //returns the number of sentences within the string
    int sentence_count = 0;
    for(int i = 0; i < strlen(text); i++){
        if (text[i] == '.' || text[i] == '!' || text[i] == '?'){
            sentence_count++;
        }
    }
return sentence_count;
}
/*
cs50/problems/2025/x/readability
:) readability.c exists
Log
checking that readability.c exists...
  
:) readability.c compiles
Log
running clang readability.c -o readability -std=c11 -ggdb -lm -lcs50...
  
:) handles single sentence with multiple words
Log
running ./readability...
sending input In my younger and more vulnerable years my father gave me some advice that I've been turning over in my mind ever since....
checking for output "Grade 7\n"...
checking for EOF...
checking that program exited with status 0...
  
:) handles punctuation within a single sentence
Log
running ./readability...
sending input There are more things in Heaven and Earth, Horatio, than are dreamt of in your philosophy....
checking for output "Grade 9\n"...
checking for EOF...
checking that program exited with status 0...
  
:) handles more complex single sentence
Log
running ./readability...
sending input Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do: once or twice she had peeped into the book her sister was reading, but it had no pictures or conversations in it, "and what is the use of a book," thought Alice "without pictures or conversation?"...
checking for output "Grade 8\n"...
checking for EOF...
checking that program exited with status 0...
  
:) handles multiple sentences
Log
running ./readability...
sending input Harry Potter was a highly unusual boy in many ways. For one thing, he hated the summer holidays more than any other time of year. For another, he really wanted to do his homework, but was forced to do it in secret, in the dead of the night. And he also happened to be a wizard....
checking for output "Grade 5\n"...
checking for EOF...
checking that program exited with status 0...
  
:) handles multiple more complex sentences
Log
running ./readability...
sending input It was a bright cold day in April, and the clocks were striking thirteen. Winston Smith, his chin nuzzled into his breast in an effort to escape the vile wind, slipped quickly through the glass doors of Victory Mansions, though not quickly enough to prevent a swirl of gritty dust from entering along with him....
checking for output "Grade 10\n"...
checking for EOF...
checking that program exited with status 0...
  
:) handles longer passages
Log
running ./readability...
sending input When he was nearly thirteen, my brother Jem got his arm badly broken at the elbow. When it healed, and Jem's fears of never being able to play football were assuaged, he was seldom self-conscious about his injury. His left arm was somewhat shorter than his right; when he stood or walked, the back of his hand was at right angles to his body, his thumb parallel to his thigh....
checking for output "Grade 8\n"...
checking for EOF...
checking that program exited with status 0...
  
:) handles multiple sentences with different punctuation
Log
running ./readability...
sending input Congratulations! Today is your day. You're off to Great Places! You're off and away!...
checking for output "Grade 3\n"...
checking for EOF...
checking that program exited with status 0...
  
:) handles questions in passage
Log
running ./readability...
sending input Would you like them here or there? I would not like them here or there. I would not like them anywhere....
checking for output "Grade 2\n"...
checking for EOF...
checking that program exited with status 0...

:) handles reading level before Grade 1
Log
running ./readability...
sending input One fish. Two fish. Red fish. Blue fish....
checking for output "Before Grade 1\n"...
checking for EOF...
checking that program exited with status 0...
  
:) handles reading level at Grade 16+
Log
running ./readability...
sending input A large class of computational problems involve the determination of properties of graphs, digraphs, integers, arrays of integers, finite families of finite sets, boolean formulas and elements of other countable domains....
checking for output "Grade 16+\n"...
checking for EOF...
checking that program exited with status 0...
*/
